#+TITLE: Alex Birdsall
#+SUBTITLE: Full Stack Software Engineer
#+description: The resumé of Alex Birdsall, full stack software engineer
#+options: html-link-use-abs-url:nil html-postamble:nil html-preamble:nil html-scripts:t toc:nil
#+options: html-style:t html5-fancy:t tex:t
#+html_doctype: html5
#+html_container: div
#+keywords:
#+html_link_home:
#+html_link_up:
#+html_mathjax:
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./solarized-light.css" />
#+html_head_extra:
#+infojs_opt:
#+creator:
#+latex_header:

* Work Experience
** Indiegogo
- rails
- vue/nuxt
- elixir
- typescript
- cypress
- redis

For two and a half years, I worked as a full-stack developer at Indiegogo. I helped rewrite the
legacy payment processing and checkout experience from angularJS to vue; I implemented a new suite
of integration tests (including its CI and github integration) using Cypress, leading to faster test
runs (and thus cheaper CI bills), fewer test flakes, and a more interactive, debugger-friendly
developer experience; I personally designed and implemented a total rewrite of the advertising
system campaigners rely on after facebook changed their policies in the wake of iOS 14 privacy
updates, which required close coordination with nontechnical stakeholders both internal and
external; and I participated in the design and implementation of an upcoming product, a new web app
to help campaigners manage inventory, shipping, and backer communication. I specifically was
responsible for the new product's frontend architecture and testing strategy. With its Elixir
backend and an aggressively prerendered vue frontend, the site performance dramatically outperformed
the legacy Indiegogo website (particularly its time to first byte, largest contentful paint, and
time to interactive measurements) while using similar technologies to minimize the learning curve
for other devs and unblock future "upstreaming" of improvements to the indiegogo.com frontend.
** SigFig
   - typescript
   - scala
   - angularJS
   - frontend builds
   - react
   - A/B testing

     My first role at SigFig was as an angularJS dev. Along with developing unit-tested features and
     fixing bugs, I helped redesign the build system of a large whitelabeled typescript app to use
     ES2015 modules and manage dependencies with npm or yarn; I converted hundreds of files to the
     new system during the migration. I personally refactored the build system to decouple its new
     build tool from its old one, significantly simplifying its configuration. I also designed the
     component A/B testing API and rewrote its integration with a 3rd-party user assignment backend,
     using a modular design so that the testing backend could easily be replaced by a better
     alternative down the line. I was also involved in the early stages of work with a new frontend
     application using typescript and react.

     Soon after, I transfered over to work on building the Scala backend service which supports that
     product. I helped spec out the REST API, and I wrote code which aggregated and composed data
     from various microservices to simplify complex, paperwork-heavy workflows.
** Legal Information Institute, Cornell University Law School
   - ES2015
   - build scripts
   - browser caching

     Cornell Law School picked up the Lawfetcher project, rebranding it as RIO (Read It Online) and
     hiring me to maintain and expand it. I refactored and completed test coverage of the domain
     logic; wrote code to parse a broader set of citation types and link to more sources; converted
     the build process to transpile modular ES2015 application code and tests; and implemented a
     [[http://guides.rubyonrails.org/asset_pipeline.html#what-is-fingerprinting-and-why-should-i-care-questionmark][filename fingerprinting]] system to manage browser caching, enabling both frequent, iterative
     code deployment and efficient loading.
** The Emoji Foundation
   - php 7
   - Apache
   - build scripts
   - SEO

     As a consultant, I did freelance work for The Emoji Foundation's crowdsourced Emoji Dictionary.
     The work focused on human-readable URLs, rewriting database queries and building indexes for
     clarity and efficiency, and other SEO and performance fundamentals, as well as extracting
     shared templates and refactoring old code for better semantics and maintainability.

** Flock
   - Rails 4
   - Middleman
   - SCSS
   - encryption & authentication

     As software engineer for an HR and compliance startup, I worked with the entire stack from
     stylesheets to server ops. I maintained Middleman static sites for the company's landing page
     and blog as well as its Rails app. I personally implemented secure and user-friendly
     integrations with TraxPayroll and Greenhouse.io, which involved complicated data mapping,
     multiple forms of encryption, and, at times, working with out-of-date and contradictory
     documentation. I organized both the stylesheets and javascript assets, spanning hundreds of
     files (some containing several thousands of lines); and in general, worked hard to model and
     advocate for consistency of data modeling, clear and explicit API boundaries, and well-designed
     abstraction on a codebase, initially built by foreign contractors, that left much to be desired
     in those regards.
** Lawfetcher
   - JavaScript
   - regular expressions
   - browserify

     A freelance project in collaboration with Emeritus Prof. Peter W. Martin of Cornell Law. A free
     tool for legal writing, it semantically parses US legal citations and programmatically builds
     direct links to the full text in various free and subscription services. More regular
     expressions than you can shake a stick at.

** magoosh (?)

* Education
** Dev Bootcamp, 2014
   - programming & web fundamentals
   - git & *nix command line
   - Ruby & Rails
   - JavaScript, HTML, & CSS

     An immersive 19-week web development program. Over the final 9 weeks alone, I worked over 1000
     hours at the San Francisco campus in an intensely collaborative environment that emphasized
     hands-on learning, empathy, communication, and problem-solving.

** Cornell College, class of '08
-  B.A. in English, minor in Music
-  2007 Winnifred Van Etten Award for Creative and Scholarly Excellence

   I chose my subjects through an interest in how human expression is shaped by the logical systems
   it exists within, like syntax, grammar, and tonal harmony. I was trained to evaluate writing for
   organization, style, and clarity. I have found this to be a surprisingly sound foundation for
   programming.
